name=LTC6915_PGA
version=1.0.0
author= Arda Bildik (Bildik Tech Labs)
maintainer=Arda Bildik <arda@bildiktech.com>
sentence=Library for the Analog Devices LTC6915 Zero-Drift Programmable Gain Amplifier.
paragraph=This is a library for the LTC6915 PGA using SPI.
category=Signal Input/Output
url=https://github.com//arda-bildik/LTC6915_PGA_Library
